### ISSUE TITLE
Create LLM with descriptions for other tasks

### ISSUE THREAD

**Issue by c-salomonsen** [axdeux/Generative-AI-project#1]
LLM is responsible for generating the description and prompt for the diffusion image generation model as well as sound generating model.

- @Sigurdah creates LLM within specifications.
- @axdeux takes main charge on stable diffusion image generation, check out [this link](https://huggingface.co/docs/diffusers/quicktour)
- @salomaestro takes main charge on sound generation.

**Comment by Sigurdah** [comment]
Here are some examples of descriptions from already existing pokemon created by chatGPT.

Pikachu
Type: Electric
Description: Pikachu is one of the most iconic Pokémon, known for its pivotal role as Ash's companion in the Pokémon anime series. It evolves from Pichu and can evolve into Raichu with the use of a Thunder Stone.
Real World Comparison: Mouse
Visual Description: Pikachu is a small, chubby, and adorable yellow rodent-like creature with long yellow ears tipped with black, a small mouth, brown eyes, and two red circles on its cheeks. Its fur is smooth and it has a tail in the shape of a lightning bolt.
Signature Cry: Pikachu's cry is high-pitched, especially notable for its "Pika-Pika" sound, which is sharp and cheerful.
Squirtle
Type: Water
Description: Squirtle is a Water-type Pokémon that resembles a small turtle. It can evolve into Wartortle and eventually into Blastoise, gaining more power and bulk with each evolution.
Real World Comparison: Turtle
Visual Description: Squirtle has a smooth, blue skin with a cream-colored underside and a shell that is a darker shade of blue. Its eyes are large and it has a small, smiling mouth, giving it a friendly appearance. The tail is small and curly.
Signature Cry: Squirtle's cry is a bubbly and watery sound, reflecting its aquatic nature, typically a soft trilling that is soothing.
Mewtwo
Type: Psychic
Description: Mewtwo is a legendary Psychic-type Pokémon created from the DNA of Mew, one of the rarest Pokémon. It is known for its incredible psychic abilities and is often regarded as one of the most powerful Pokémon.
Real World Comparison: Feline
Visual Description: Mewtwo stands upright and has a sleek, humanoid body covered in pale purple fur. Its eyes are bright purple, and it has a long, thin tail. Its structure is muscular yet streamlined for agility.
Signature Cry: Mewtwo's cry is deep and telepathic-sounding, often resonating with a metallic echo, reflecting its mysterious and formidable nature.
Blastoise
Type: Water
Description: Blastoise is the final evolutionary stage of Squirtle, following Wartortle. Known for the powerful water cannons on its back, Blastoise can shoot water with enough force to penetrate steel.
Real World Comparison: Tortoise
Visual Description: Blastoise is a large, bipedal turtle with a massive, blue shell featuring two powerful water cannons. It has a rugged, blue body, small brown eyes, and a serious expression on its face.
Signature Cry: Blastoise has a deep, roaring cry, similar to the sound of a cannon firing, which is intimidating and powerful.
Treecko
Type: Grass
Description: Treecko, a Grass-type Pokémon, is known for its cool demeanor and is the first stage in its evolutionary line, leading to Grovyle and then Sceptile. It has abilities that allow it to scale vertical walls.
Real World Comparison: Gecko
Visual Description: Treecko is small and sleek, primarily green with a light underskin and a long, curled tail. It has large, yellow eyes and feet that are big compared to its body, adapted for climbing.
Signature Cry: Treecko's cry is sharp and quick, similar to a chirp, which reflects its alert and agile nature.
Rayquaza
Type: Dragon / Flying
Description: Rayquaza is a legendary Pokémon that is part of the weather trio, along with Kyogre and Groudon. It has the ability to calm the other two members of the trio. It is known for living in the ozone layer and rarely descending to the ground.
Real World Comparison: Serpent
Visual Description: Rayquaza is a long, serpentine creature with a green body and yellow patterns that run along its length. It has an imposing presence with sharp, red eyes and fins along its body that give it a majestic and fearsome look.
Signature Cry: Rayquaza's cry is a majestic and echoing roar, powerful enough to be heard across great distances, resonating through the skies.
